# Generated by Django 3.2 on 2022-06-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyect',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Fin'),
        ),
        migrations.AlterField(
            model_name='proyect',
            name='start_date',
            field=models.DateField(verbose_name='Fecha Inicio'),
        ),
    ]
