# Generated by Django 3.2 on 2022-06-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20220613_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyect',
            name='status',
            field=models.CharField(choices=[('1', 'Detenido'), ('2', 'Desarrollo'), ('3', 'Finalizado')], default='1', max_length=50, verbose_name='Estatus'),
            preserve_default=False,
        ),
    ]
