# Generated by Django 3.2 on 2022-06-13 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_proyect_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('language', models.CharField(choices=[('python', 'Python'), ('php', 'PHP'), ('.net', '.Net')], max_length=50, verbose_name='Lenguaje')),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='Spring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('start_date', models.DateField(verbose_name='Fecha Inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha Fin')),
                ('total_hours', models.FloatField()),
            ],
            options={
                'ordering': ('-name', '-start_date'),
            },
        ),
        migrations.AlterField(
            model_name='proyect',
            name='status',
            field=models.CharField(choices=[('Detenido', 'Detenido'), ('Desarrollo', 'Desarrollo'), ('Finalizado', 'Finalizado')], max_length=50, verbose_name='Estatus'),
        ),
        migrations.CreateModel(
            name='SpringConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.developer')),
                ('spring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.spring')),
            ],
        ),
        migrations.AddField(
            model_name='spring',
            name='proyect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.proyect'),
        ),
    ]
